name: build-tools-jdk-images

on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * 0"
  push:
    branches: 
      - main
    paths:
      - "jdk/tools-jdk.sh"
      - "jdk/git-jdk/**"
      - "jdk/docker-jdk/**"
      - "jdk/dind-jdk/**"
      - ".github/workflows/tools-jdk.yaml"

jobs:
  images-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_NAME }}
          password: ${{ secrets.CR_PAT }}
      - name: Set Env
        run: echo "TIMESTAMP=$(date +%y.%m.%d.%H.%M)" >> $GITHUB_ENV
      - name: Docker build & push
        env:
          PROJECT_VERSION: 1.0.0
          TAG_VERSION: ${{ github.run_number }}
          CI_REGISTRY: ghcr.io
          PROJECT_DIR: ${{ github.workspace }}
          PLATFORM: linux/amd64,linux/arm64
        run: |
          sudo apt update && sudo apt install curl jq &&
          chmod +x jdk/tools-jdk.sh && jdk/tools-jdk.sh
